# Generated by Django 4.0.2 on 2022-05-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shecodesuser',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shecodesuser',
            name='is_shecodes_admin',
            field=models.BooleanField(default=False),
        ),
    ]
