# Generated by Django 2.2.28 on 2022-05-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220529_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shecodesuser',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shecodesuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shecodesuser',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
