# Generated by Django 2.2.28 on 2022-05-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_shecodesuser_first_name_alter_shecodesuser_id'),
        ('users', '0005_alter_shecodesuser_first_name_alter_shecodesuser_id'),
    ]

    operations = [
    ]
