# Generated by Django 4.0.2 on 2022-05-21 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='win_wall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stickynotes', to='winwall.winwall'),
        ),
    ]
