# Generated by Django 2.2.28 on 2022-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
