# Generated by Django 4.0.2 on 2022-05-21 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0002_collection_winwall_collection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winwall',
            name='collection_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='winwall.collection'),
        ),
    ]
