# Generated by Django 4.0.2 on 2022-05-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0002_alter_stickynote_win_wall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winwall',
            old_name='user_id',
            new_name='owner',
        ),
    ]
