# Generated by Django 4.0.2 on 2022-05-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0003_winwall_collection_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
    ]
