# Generated by Django 4.0.2 on 2022-05-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0003_rename_user_id_winwall_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winwall',
            name='is_open',
        ),
    ]
