# Generated by Django 4.0.2 on 2022-05-31 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0003_alter_collection_id_alter_stickynote_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='slug',
        ),
    ]
