# Generated by Django 4.0.2 on 2022-05-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0004_remove_collection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winwall',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='winwall',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='win_wall_collections', to='winwall.collection'),
        ),
    ]
