# Generated by Django 4.0.2 on 2022-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0004_remove_winwall_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='is_approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stickynote',
            name='is_archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
