# Generated by Django 4.0.2 on 2022-05-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winwall', '0005_stickynote_is_approved_stickynote_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='is_archived',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
